[project]
name = "aib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "winter25",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]

[tool.uv.sources]
winter25 = { path = "winter25" }
